<main id="contenido">
			<h1 class="img-carrito2" id="titulo_pagina"> ¿quienes somos? </h1>
			<section class="img-carrito2" id="caja_pagina">
				<article id="caja_texto">
						<b style="font-size: 18px;">Bruno Gas S.A. es una de las nueve empresas de distribución de gas natural en la República Argentina, que surgieron con la privatización de la Empresa de Gas del Estado, pero, a diferencia de las demás distribuidoras Bruno Gas no disponía de ningún tipo de infraestructura de gas en el área. Nuestra Misión es edificar la Relación con nuestros Clientes al brindarles más y mejores Servicios y Soluciones relacionados con su consumo de Energía, sea en su establecimiento, en sus vehículos o en sus domicilios. Los valores que cultivamos en nuestra empresa, necesarios para el logro de los objetivos, son la iniciativa personal educada con el profesionalismo en nuestra tarea, cualquiera sea la que desempeñemos, la disposición para integrar un equipo de alta performance y el afán de progreso deben distinguirnos. La satisfacción del cliente como nuestro principal esmero, que se manifiesta antes, durante y después del encuentro personal con el cliente y abarca: El conocimiento y comprensión de las necesidades del cliente; el mejor asesoramiento que le podamos dar, antes, durante y después de la Venta; la atención personalizada en la venta; un esmerado servicio de posventa; y la atención de garantas. Otro valores destacables son: la Garantía y la Confianza de los Productos y Servicios que comercializamos; la seguridad y el cumplimiento de la normativa, como camino para diferenciarnos y para tener el futuro; la innovación y la actualización, poniendo al alcance del cliente las mejores soluciones energéticas de las que el mercado disponga.  La cabal comprensión que todas las tareas: de ventas; administrativas y de conducción son fundamentales,  igualmente importantes de cara al cliente y tienen su razón de ser en el cliente. La difusión y persecución de los objetivos con el equipo, y la solicitud de ayuda cuando no se alcance el objetivo.	<br><br/>
						</b>
				</article>
				<img class="img-carrito2 bg-white row text-dark mt-2 mb-2 ml-2 mr-4" src="<?php echo base_url("/assets/imagenes/bgas.png");?>">
			</section>
		</main>